//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cart
    {
        public int recordID { get; set; }
        public string cartID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
    }
}
