//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserRole
    {
        public int userroleID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> roleID { get; set; }
    
        public virtual tbl_Role tbl_Role { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
